#ChangeLog Pro Configuration
#Sat Dec 27 15:16:28 CET 2025
changelog.file=CHANGELOG.md
git.auto.stage=true
git.provider=GITHUB
initialized=true
issue.tracker=GITHUB_ISSUES
issue.tracker.url=https\://github.com/aboushaheed/changelogpro/issues
repo.url=https\://github.com/aboushaheed/changelogpro
